[build]
builder = "NIXPACKS"

[build.nixpacksDependencies]
packages = ["chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-freefont"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
